# Generated by Django 5.2.7 on 2025-11-02 20:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_user_is_admin_remove_user_is_coach_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.coach",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="college",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="player",
            name="player_id",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tournament_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_awarded", models.DateField(default=django.utils.timezone.now)),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.match",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="core.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerSport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("cricket", "Cricket"),
                            ("football", "Football"),
                            ("basketball", "Basketball"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "role_in_sport",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("started_on", models.DateField(default=django.utils.timezone.now)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sports",
                        to="core.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "sport")},
            },
        ),
        migrations.CreateModel(
            name="CricketStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matches", models.PositiveIntegerField(default=0)),
                ("runs", models.PositiveIntegerField(default=0)),
                ("balls_faced", models.PositiveIntegerField(default=0)),
                ("wickets", models.PositiveIntegerField(default=0)),
                ("overs_bowled", models.FloatField(default=0)),
                ("highest_score", models.PositiveIntegerField(default=0)),
                ("average", models.FloatField(default=0)),
                ("strike_rate", models.FloatField(default=0)),
                ("catches", models.PositiveIntegerField(default=0)),
                ("stumpings", models.PositiveIntegerField(default=0)),
                (
                    "player_sport",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cricket_stats",
                        to="core.playersport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_role", models.CharField(max_length=20)),
                ("new_role", models.CharField(max_length=20)),
                ("changed_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
