# Generated by Django 5.2.7 on 2025-11-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_player_coach_player_college_player_is_public_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="player_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
